trigger:
- main
pool:
 vmImage: ubuntu-latest
steps:
- task: UsePythonVersion@0
  displayName: "Set Python version to 3.10"
  inputs:
  versionSpec: '3.10'
  architecture: 'x64'
- bash: |
   if [ -f extensions.csproj ]
   then
       dotnet build extensions.csproj --output ./bin
   fi
   pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
   rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
   includeRootFolder: false
   archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
   artifactName: 'drop'
- task: AzureFunctionApp@2
   inputs:
     connectedServiceNameARM: coicsaazurefunctionconn
     appType: functionAppLinux
     appName: COICSADataQualityCheck
     package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip